name: Build, Tag, Release, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Tag, Release, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Get the current version from package.json
        id: version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create a temporary branch for the build output
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git checkout --orphan build-output-branch
          git reset --hard
          mkdir -p build_output
          cp -r dist/* .
          git add . :!node_modules/ :!dist/ :!.parcel-cache
          git commit -m "Add build output for version ${{ env.VERSION }}"

      - name: Create a tag from the build output branch
        run: |
          git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          body: |
            Changes in this Release:
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 20m
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            curl -LJO https://github.com/serhatkaya/shift/archive/refs/tags/v${{ env.VERSION }}.zip
            unzip -o shift-v${{ env.VERSION }}.zip -d ./
            rm shift-v${{ env.VERSION }}.zip

      - name: Cleanup
        run: git checkout main
